//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace ATSWeb.Silverlight.EmployeeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeServiceReference.EmployeesWebServiceSoap")]
    public interface EmployeesWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FindByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseClass))]
        System.IAsyncResult BeginFindByID(int entityID, System.AsyncCallback callback, object asyncState);
        
        ATSWeb.Silverlight.EmployeeServiceReference.EntityResultOfEmployees EndFindByID(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FindAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseClass))]
        System.IAsyncResult BeginFindAll(System.AsyncCallback callback, object asyncState);
        
        ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees EndFindAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FindByManagerID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseClass))]
        System.IAsyncResult BeginFindByManagerID(int managerID, System.AsyncCallback callback, object asyncState);
        
        ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees EndFindByManagerID(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FindByDeptCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseClass))]
        System.IAsyncResult BeginFindByDeptCode(string deptCode, System.AsyncCallback callback, object asyncState);
        
        ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees EndFindByDeptCode(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityResultOfEmployees : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Employees returnedEntityField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Employees ReturnedEntity {
            get {
                return this.returnedEntityField;
            }
            set {
                this.returnedEntityField = value;
                this.RaisePropertyChanged("ReturnedEntity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employees : BaseClass {
        
        private Specialist specialistField;
        
        private Company companyField;
        
        private Qualifications qualificationsField;
        
        private Title titleField;
        
        private System.DateTime endDateField;
        
        private Nationality nationalityField;
        
        private System.DateTime startDateField;
        
        private Category categoryField;
        
        private Rank rankField;
        
        private string nameField;
        
        private Department departmentField;
        
        private int userIDField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Specialist Specialist {
            get {
                return this.specialistField;
            }
            set {
                this.specialistField = value;
                this.RaisePropertyChanged("Specialist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Company Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Qualifications Qualifications {
            get {
                return this.qualificationsField;
            }
            set {
                this.qualificationsField = value;
                this.RaisePropertyChanged("Qualifications");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Title Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Nationality Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
                this.RaisePropertyChanged("Nationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Category Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Rank Rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
                this.RaisePropertyChanged("Rank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Department Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Specialist : BaseClass {
        
        private string nameField;
        
        private decimal idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Department))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rank))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Category))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Nationality))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Title))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Qualifications))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Company))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Specialist))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employees))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class BaseClass : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityListResultOfEmployees : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Employees[] returnedEntitiesField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Employees[] ReturnedEntities {
            get {
                return this.returnedEntitiesField;
            }
            set {
                this.returnedEntitiesField = value;
                this.RaisePropertyChanged("ReturnedEntities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Department : BaseClass {
        
        private decimal shortCodeField;
        
        private decimal codeField;
        
        private string shortNameField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal ShortCode {
            get {
                return this.shortCodeField;
            }
            set {
                this.shortCodeField = value;
                this.RaisePropertyChanged("ShortCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
                this.RaisePropertyChanged("ShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Rank : BaseClass {
        
        private string nameField;
        
        private decimal idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Category : BaseClass {
        
        private string nameField;
        
        private float idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Nationality : BaseClass {
        
        private string nameField;
        
        private decimal idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Title : BaseClass {
        
        private string nameField;
        
        private decimal idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Qualifications : BaseClass {
        
        private string nameField;
        
        private decimal idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Company : BaseClass {
        
        private string phoneField;
        
        private string addressField;
        
        private string descriptionField;
        
        private string nameField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeesWebServiceSoapChannel : ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FindByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FindByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ATSWeb.Silverlight.EmployeeServiceReference.EntityResultOfEmployees Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ATSWeb.Silverlight.EmployeeServiceReference.EntityResultOfEmployees)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FindAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FindAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FindByManagerIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FindByManagerIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FindByDeptCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FindByDeptCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeesWebServiceSoapClient : System.ServiceModel.ClientBase<ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap>, ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap {
        
        private BeginOperationDelegate onBeginFindByIDDelegate;
        
        private EndOperationDelegate onEndFindByIDDelegate;
        
        private System.Threading.SendOrPostCallback onFindByIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginFindAllDelegate;
        
        private EndOperationDelegate onEndFindAllDelegate;
        
        private System.Threading.SendOrPostCallback onFindAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginFindByManagerIDDelegate;
        
        private EndOperationDelegate onEndFindByManagerIDDelegate;
        
        private System.Threading.SendOrPostCallback onFindByManagerIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginFindByDeptCodeDelegate;
        
        private EndOperationDelegate onEndFindByDeptCodeDelegate;
        
        private System.Threading.SendOrPostCallback onFindByDeptCodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public EmployeesWebServiceSoapClient() {
        }
        
        public EmployeesWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeesWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeesWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeesWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<FindByIDCompletedEventArgs> FindByIDCompleted;
        
        public event System.EventHandler<FindAllCompletedEventArgs> FindAllCompleted;
        
        public event System.EventHandler<FindByManagerIDCompletedEventArgs> FindByManagerIDCompleted;
        
        public event System.EventHandler<FindByDeptCodeCompletedEventArgs> FindByDeptCodeCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap.BeginFindByID(int entityID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFindByID(entityID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATSWeb.Silverlight.EmployeeServiceReference.EntityResultOfEmployees ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap.EndFindByID(System.IAsyncResult result) {
            return base.Channel.EndFindByID(result);
        }
        
        private System.IAsyncResult OnBeginFindByID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int entityID = ((int)(inValues[0]));
            return ((ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap)(this)).BeginFindByID(entityID, callback, asyncState);
        }
        
        private object[] OnEndFindByID(System.IAsyncResult result) {
            ATSWeb.Silverlight.EmployeeServiceReference.EntityResultOfEmployees retVal = ((ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap)(this)).EndFindByID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFindByIDCompleted(object state) {
            if ((this.FindByIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FindByIDCompleted(this, new FindByIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FindByIDAsync(int entityID) {
            this.FindByIDAsync(entityID, null);
        }
        
        public void FindByIDAsync(int entityID, object userState) {
            if ((this.onBeginFindByIDDelegate == null)) {
                this.onBeginFindByIDDelegate = new BeginOperationDelegate(this.OnBeginFindByID);
            }
            if ((this.onEndFindByIDDelegate == null)) {
                this.onEndFindByIDDelegate = new EndOperationDelegate(this.OnEndFindByID);
            }
            if ((this.onFindByIDCompletedDelegate == null)) {
                this.onFindByIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFindByIDCompleted);
            }
            base.InvokeAsync(this.onBeginFindByIDDelegate, new object[] {
                        entityID}, this.onEndFindByIDDelegate, this.onFindByIDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap.BeginFindAll(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFindAll(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap.EndFindAll(System.IAsyncResult result) {
            return base.Channel.EndFindAll(result);
        }
        
        private System.IAsyncResult OnBeginFindAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap)(this)).BeginFindAll(callback, asyncState);
        }
        
        private object[] OnEndFindAll(System.IAsyncResult result) {
            ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees retVal = ((ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap)(this)).EndFindAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFindAllCompleted(object state) {
            if ((this.FindAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FindAllCompleted(this, new FindAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FindAllAsync() {
            this.FindAllAsync(null);
        }
        
        public void FindAllAsync(object userState) {
            if ((this.onBeginFindAllDelegate == null)) {
                this.onBeginFindAllDelegate = new BeginOperationDelegate(this.OnBeginFindAll);
            }
            if ((this.onEndFindAllDelegate == null)) {
                this.onEndFindAllDelegate = new EndOperationDelegate(this.OnEndFindAll);
            }
            if ((this.onFindAllCompletedDelegate == null)) {
                this.onFindAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFindAllCompleted);
            }
            base.InvokeAsync(this.onBeginFindAllDelegate, null, this.onEndFindAllDelegate, this.onFindAllCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap.BeginFindByManagerID(int managerID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFindByManagerID(managerID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap.EndFindByManagerID(System.IAsyncResult result) {
            return base.Channel.EndFindByManagerID(result);
        }
        
        private System.IAsyncResult OnBeginFindByManagerID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int managerID = ((int)(inValues[0]));
            return ((ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap)(this)).BeginFindByManagerID(managerID, callback, asyncState);
        }
        
        private object[] OnEndFindByManagerID(System.IAsyncResult result) {
            ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees retVal = ((ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap)(this)).EndFindByManagerID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFindByManagerIDCompleted(object state) {
            if ((this.FindByManagerIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FindByManagerIDCompleted(this, new FindByManagerIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FindByManagerIDAsync(int managerID) {
            this.FindByManagerIDAsync(managerID, null);
        }
        
        public void FindByManagerIDAsync(int managerID, object userState) {
            if ((this.onBeginFindByManagerIDDelegate == null)) {
                this.onBeginFindByManagerIDDelegate = new BeginOperationDelegate(this.OnBeginFindByManagerID);
            }
            if ((this.onEndFindByManagerIDDelegate == null)) {
                this.onEndFindByManagerIDDelegate = new EndOperationDelegate(this.OnEndFindByManagerID);
            }
            if ((this.onFindByManagerIDCompletedDelegate == null)) {
                this.onFindByManagerIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFindByManagerIDCompleted);
            }
            base.InvokeAsync(this.onBeginFindByManagerIDDelegate, new object[] {
                        managerID}, this.onEndFindByManagerIDDelegate, this.onFindByManagerIDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap.BeginFindByDeptCode(string deptCode, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFindByDeptCode(deptCode, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap.EndFindByDeptCode(System.IAsyncResult result) {
            return base.Channel.EndFindByDeptCode(result);
        }
        
        private System.IAsyncResult OnBeginFindByDeptCode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string deptCode = ((string)(inValues[0]));
            return ((ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap)(this)).BeginFindByDeptCode(deptCode, callback, asyncState);
        }
        
        private object[] OnEndFindByDeptCode(System.IAsyncResult result) {
            ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees retVal = ((ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap)(this)).EndFindByDeptCode(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFindByDeptCodeCompleted(object state) {
            if ((this.FindByDeptCodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FindByDeptCodeCompleted(this, new FindByDeptCodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FindByDeptCodeAsync(string deptCode) {
            this.FindByDeptCodeAsync(deptCode, null);
        }
        
        public void FindByDeptCodeAsync(string deptCode, object userState) {
            if ((this.onBeginFindByDeptCodeDelegate == null)) {
                this.onBeginFindByDeptCodeDelegate = new BeginOperationDelegate(this.OnBeginFindByDeptCode);
            }
            if ((this.onEndFindByDeptCodeDelegate == null)) {
                this.onEndFindByDeptCodeDelegate = new EndOperationDelegate(this.OnEndFindByDeptCode);
            }
            if ((this.onFindByDeptCodeCompletedDelegate == null)) {
                this.onFindByDeptCodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFindByDeptCodeCompleted);
            }
            base.InvokeAsync(this.onBeginFindByDeptCodeDelegate, new object[] {
                        deptCode}, this.onEndFindByDeptCodeDelegate, this.onFindByDeptCodeCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap CreateChannel() {
            return new EmployeesWebServiceSoapClientChannel(this);
        }
        
        private class EmployeesWebServiceSoapClientChannel : ChannelBase<ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap>, ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap {
            
            public EmployeesWebServiceSoapClientChannel(System.ServiceModel.ClientBase<ATSWeb.Silverlight.EmployeeServiceReference.EmployeesWebServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginFindByID(int entityID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = entityID;
                System.IAsyncResult _result = base.BeginInvoke("FindByID", _args, callback, asyncState);
                return _result;
            }
            
            public ATSWeb.Silverlight.EmployeeServiceReference.EntityResultOfEmployees EndFindByID(System.IAsyncResult result) {
                object[] _args = new object[0];
                ATSWeb.Silverlight.EmployeeServiceReference.EntityResultOfEmployees _result = ((ATSWeb.Silverlight.EmployeeServiceReference.EntityResultOfEmployees)(base.EndInvoke("FindByID", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginFindAll(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("FindAll", _args, callback, asyncState);
                return _result;
            }
            
            public ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees EndFindAll(System.IAsyncResult result) {
                object[] _args = new object[0];
                ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees _result = ((ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees)(base.EndInvoke("FindAll", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginFindByManagerID(int managerID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = managerID;
                System.IAsyncResult _result = base.BeginInvoke("FindByManagerID", _args, callback, asyncState);
                return _result;
            }
            
            public ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees EndFindByManagerID(System.IAsyncResult result) {
                object[] _args = new object[0];
                ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees _result = ((ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees)(base.EndInvoke("FindByManagerID", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginFindByDeptCode(string deptCode, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = deptCode;
                System.IAsyncResult _result = base.BeginInvoke("FindByDeptCode", _args, callback, asyncState);
                return _result;
            }
            
            public ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees EndFindByDeptCode(System.IAsyncResult result) {
                object[] _args = new object[0];
                ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees _result = ((ATSWeb.Silverlight.EmployeeServiceReference.EntityListResultOfEmployees)(base.EndInvoke("FindByDeptCode", _args, result)));
                return _result;
            }
        }
    }
}
